require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'NuSearchPharma' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # user permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  
  # # Firebase SDK
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Messaging'
  # pod 'Firebase/Core', '~> 6.5.0'
  
  target 'NuSearchPharmaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
